### ISSUE TITLE
Programador não é muito bom não

### ISSUE THREAD

**Issue by olliveiragusttavo** [MatheusAntonioF/counter-tv-shows#6]
O bug que vou reportar é do programador, ele não é muito bom. Deveria trocar ele, aí os problemas desse repositório seriam resolvidos.

**Comment by panacaqui** [comment]
Olha só, é a issue #6 já

**Comment by MatheusAntonioF** [comment]
Respeita o pae, cê trampa com php

**Comment by panacaqui** [comment]
Me respeita eu querida! Trampo com PHP mas não é meu foco. Essa vergonha eu não passo

**Comment by MatheusAntonioF** [comment]
Vergonha quem passa é a galera que trabalha contigo KKKKKKKKKKKKKKKKKKKKKKKKKKKKK
